version: '3'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    command: start-dev
    ports:
      - 8080:8080

  echo:
    image: ealen/echo-server:0.7.0
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    ports:
      - 3333:80
