version: '3'
services:
  keycloak:
    container_name: prixi-openidc-keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    command: start-dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    ports:
      - 8080:8080

  echo-ws:
    image: jmalloc/echo-server:0.3.6
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    ports:
      - 4444:8080

