name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start docker compose
        run: docker-compose up -d --build

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      - name: Init Keycloak
        run: bash bin/0-init-keycloak.sh

      - name: Run tests
        run: yarn test

      - name: Stop containers
        if: always()
        run: docker-compose down

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
